### ISSUE TITLE
Can't align using saved model

### ISSUE THREAD

**Issue by JoFrhwld** [MontrealCorpusTools/Montreal-Forced-Aligner#104]
I've trained a model using `mfa_train_and_align`, and would like to reuse it. When I run the aligner like so

    bin/mfa_align corpus/ dictionary model/model.zip output/

it successfully gets through set up, but then gives me the following error:

    Setting up corpus information...
    Number of speakers in corpus: 25, average number of utterances per speaker: 589.36
    Creating dictionary information...
    Setting up corpus_data directory...
    Generating base features (mfcc)...
    Calculating CMVN...
    Done with setup.
    Traceback (most recent call last):
      File "aligner/command_line/align.py", line 224, in <module>
      File "aligner/command_line/align.py", line 181, in validate_args
      File "aligner/command_line/align.py", line 141, in align_corpus
      File "aligner/aligner/pretrained.py", line 93, in align
      File "aligner/multiprocessing.py", line 322, in align
    aligner.exceptions.AlignmentError: There were 3 job(s) with errors.  For more information, please see the following logs:

    /Users/jofrhwld/Documents/MFA/edinburgh_to_align/align/log/align.final.0.log
    /Users/jofrhwld/Documents/MFA/edinburgh_to_align/align/log/align.final.1.log
    /Users/jofrhwld/Documents/MFA/edinburgh_to_align/align/log/align.final.2.log

When I look at the relevant log files, I think the relevant error is this:

    ERROR (gmm-align-compiled[5.4.251~1-094d2]:LogLikelihoodZeroBased():decodable-am-diag-gmm.cc:50) Dim mismatch: data dim = 39 vs. model dim = 40

I found a related discussion on the Kaldi page here: [https://sourceforge.net/p/kaldi/discussion/1355348/thread/028ffd7f/](https://sourceforge.net/p/kaldi/discussion/1355348/thread/028ffd7f/)

The answer that seemed to fix things was:

> Actually, since the data dim is 39 and the model dim is 40, I think it's
most likely that he is using delta+accel features but the model expected
LDA+MLLT features.
Lucian, have a look at the decoding command line that was used when you
decoded your original data where you trained the model. Most likely it
will have a splicing step (splice-feats) followed by a projection step
(transform-feats)- you should try to replicate that when you decode.
If you are using a decoding script, it will automatically pick up the
LDA+MLLT features if you copy the final.mat to the directory where your
final.mdl exists. Also make sure to copy splice_opts and cmvn_opts to that
directory.

Is there something that I can do either with the model I've trained, or in re-training to fix this problem? Here's my training config file.

```
beam: 10
retry_beam: 40

features:
  type: "mfcc"
  use_energy: false
  frame_shift: 10

training:
  - monophone:
      num_iterations: 40
      max_gaussians: 1000
      subset: 2000
      boost_silence: 1.25

  - triphone:
      num_iterations: 35
      num_leaves: 2000
      max_gaussians: 10000
      cluster_threshold: -1
      subset: 5000
      boost_silence: 1.25
      power: 0.25

  - lda:
      num_leaves: 2500
      max_gaussians: 15000
      subset: 10000
      num_iterations: 35
      features:
          splice_left_context: 3
          splice_right_context: 3

  - sat:
      num_leaves: 2500
      max_gaussians: 15000
      silence_weight: 0.0
      fmllr_update_type: "diag"
      subset: 30000
      features:
          lda: true

  - sat:
      calc_pron_probs: true
      num_leaves: 4200
      max_gaussians: 40000
      silence_weight: 0.0
      fmllr_update_type: "diag"
      subset: 30000
      features:
          lda: true
          fmllr: true
```
