### ISSUE TITLE
Feature Request: Add Dockerfile

### ISSUE THREAD

**Issue by JRMeyer** [MontrealCorpusTools/Montreal-Forced-Aligner#356]
Hi @mmcauliffe and the team :wave: 

first things first, the MFA is awesome! thanks for continuing to improve and support it:)

one feature request: include a Dockerfile for easy containerization. I know you've done work to have MFA supported in conda, but also a Dockerfile would be nice. If I get time I'll send a PR:)

**Comment by mmcauliffe** [comment]
Thanks, yeah, dockerfile is on the roadmap, so I'm hoping to tackle that for this next release, though my experiences with docker are like 5 years old at this point, so I might ask you to review any PR for it that I put together to make sure everything looks right.

**Comment by jungs1** [comment]
Creating a Dockerfile for Montreal-Forced-Aligner has been much easier after the recent 2.0 update. Before, I had to set Ubuntu as the base image, and install libopenblas-base, sox, and on top install the correct dependencies (kaldi, pynini, ngram....) inside conda's environment. (It took more than 5 minutes to build the whole thing!) 
Now that MFA relies on Conda Forge for handling dependencies, Dockerfile is as simple as below

```
FROM continuumio/miniconda3
RUN conda create -n aligner -c conda-forge montreal-forced-aligner
```

And Docker-compose may look something like this (tty flag to enable interactive shell)
```
version: "3"
services:
  aligner:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    container_name: mfa
    restart: always
    volumes:
      - ~/work/mfa_data/:/mfa_data
```
After that you simply run the docker-compose file in the background and ssh into the docker container!

```
docker-compose up -d
docker exec -it {CONTIANER_ID} bash
```

I haven't tested all the MFA commands inside this docker, just the important ones like mfa g2p and mfa align. They all seem to work. 

I am no docker expert, so there might be a better way to containerize MFA. However, I hope this helps you in any way.
