### ISSUE TITLE
[BUG] Per-speaker dictionaries not used if they share a common basename

### ISSUE THREAD

**Issue by sharvil** [MontrealCorpusTools/Montreal-Forced-Aligner#417]
Consider per-speaker dictionaries described by the following .yaml:

```yml
speaker_a: /data/speaker_a/dictionary.txt
speaker_b: /data/speaker_b/dictionary.txt
speaker_c: /data/speaker_c/dictionary.txt
```

Note that each full path is unique, so each file's contents may also be unique. When aligning, `speaker_a`'s dictionary is silently used for all speakers since they share a common `basename` (see https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/dictionary/multispeaker.py#L150-L155 and https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/blob/main/montreal_forced_aligner/models.py#L970).

One easy fix is to implement the `DictionaryModel.name` property as:
```python
@property
def name(self) -> str:
  import hashlib
  return hashlib.sha1(self.path.encode()).hexdigest()
```

Feel free to propose a better solution -- I'm sure there are plenty.
